#!/bin/bash
#SBATCH --job-name=vlcs%j
#SBATCH --output=output_vlcs/job-vlcs-%j.out
#SBATCH --error=log_vlcs/job-vlcs-%j.log
#SBATCH --time=11:59:59
#SBATCH --mem-per-cpu=5G
#SBATCH --cpus-per-task=24
#SBATCH --array=1-80

source activate dgsml_gpu

INDEXFILE=./samples_vlcs.list

INDEX=$(awk "NR==$SLURM_ARRAY_TASK_ID" $INDEXFILE)
INDEX_ARR=(`echo ${INDEX}`)
RUNNUM=${INDEX_ARR[0]}
SEED=${INDEX_ARR[1]}
RATE=${INDEX_ARR[2]}
DOMAIN=${INDEX_ARR[3]}


echo "Running: Run${RUNNUM} ${DOMAIN} ${SEED}"


DOM=("Caltech" "Labelme" "Pascal" "Sun")

dgmsl_ROOT=".."
FL_ROOT="${dgmsl_ROOT}/filelist/VLCS_list/"
LOG_ROOT="../vlcs_res"
LOG_DIR="${LOG_ROOT}/save${RATE}_${RUNNUM}_${DOM[${DOMAIN}]}"
DATAROOT="../../data/VLCS/"

MBS=128

EPOCH=1000
LR="0.001"
META_LR="0.000001"
BETA0="0.001"
BETA1="0.01"
BETA2="0.01"
STEP=10	
N_CLS=5
NUM=3
DATASET='VLCS'
python ${dgmsl_ROOT}/mainGPU.py --dataset ${DATASET} --num_classes ${N_CLS} --target_domain ${DOMAIN}  --seed ${SEED} --filelist ${FL_ROOT}  --save_logs ${LOG_DIR} --save_models ${LOG_DIR}  --save_results ${LOG_DIR} --iteration ${EPOCH} --batch_size ${MBS}  --data_root $DATAROOT --num_train_domain ${NUM} --unlabeled_rate ${RATE} --lr ${LR} --meta_lr ${META_LR} --SSL_coef ${BETA0} --gloabl_coef ${BETA1} --class_wise_coef ${BETA2} --save_step ${STEP} 
